[package]
name = "yew-app"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
dasp = "0.11.0"
log = "0.4.17"
reqwasm = "0.5.0"
serde = { version = "1.0.137", features = ["derive"] }
wasm-bindgen-futures = "0.4.30"
wasm-logger = "0.2.0"
yew = "0.19.3"
